---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

# Configuration version
# See https://golangci-lint.run/usage/configuration/#version
version: "2"

linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - gocritic
    - govet
    - revive
  settings:
    errcheck:
      # report about assignment of errors to blank identifier
      # default is false: such cases aren't reported by default.
      check-blank: true
    gocyclo:
      # minimal code complexity to report, 30 by default
      min-complexity: 15
  exclusions:
    rules:
      # Exclude specific linters from running on test files.
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst

formatters:
  enable:
    - goimports

